version: '3'

services:
  db:
    image: postgres
    working_dir: "/code/database/"
    container_name: books-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: books
    ports:
      - "5432:5432"
    volumes:
      - books_postgres:/var/lib/postgresql/data
    network_mode: bridge

  api:
    build: .
    working_dir: "/code/"
    container_name: books-api
    restart: unless-stopped
    command: uvicorn books_mobile:app --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    network_mode: bridge
    environment:
      - ENVIRONMENT=dev

volumes:
  books_postgres:
